stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  cache:
    key: ${CI_ENVIRONMENT_SLUG}
    paths:
      - node_modules/
  script:
    - yarn
    - yarn build-prod
  only:
    - /^v*/
  artifacts:
    paths:
      - build
  only:
    - /^v*/
  except:
    - branches

deploy to production:
  stage: deploy
  environment: production
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp build/ s3://$S3_BUCKET_NAME/ --recursive
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID  --paths "/*"
  only:
    - /^v*/
  except:
    - branches
  when: manual
